//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: authorization.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_FirstAuthorization_Req")]
  public partial class CMSG_FirstAuthorization_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_FirstAuthorization_Req() {}
    
    private ulong _account_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _channel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_FirstAuthorization_Resp")]
  public partial class SMSG_FirstAuthorization_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_FirstAuthorization_Resp() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _authorization_str;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"authorization_str", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authorization_str
    {
      get { return _authorization_str; }
      set { _authorization_str = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_ReconnectOnLossandAuthorization_Req")]
  public partial class CMSG_ReconnectOnLossandAuthorization_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_ReconnectOnLossandAuthorization_Req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_ConnectToNewGateway_Ntf")]
  public partial class SMSG_ConnectToNewGateway_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_ConnectToNewGateway_Ntf() {}
    
    private string _ip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _port;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint port
    {
      get { return _port; }
      set { _port = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncServerTimestamp_Ntf")]
  public partial class SMSG_SyncServerTimestamp_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncServerTimestamp_Ntf() {}
    
    private ulong _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncRandomFactor_Ntf")]
  public partial class SMSG_SyncRandomFactor_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncRandomFactor_Ntf() {}
    
    private string _random_factor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"random_factor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string random_factor
    {
      get { return _random_factor; }
      set { _random_factor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AccountDuplicateLogin_Ntf")]
  public partial class SMSG_AccountDuplicateLogin_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AccountDuplicateLogin_Ntf() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: character.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private ulong _account_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong account_id
    {
      get { return _account_id; }
      set { _account_id = value; }
    }
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _portrait;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private ulong _exp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private ulong _non_bind_gold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"non_bind_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong non_bind_gold
    {
      get { return _non_bind_gold; }
      set { _non_bind_gold = value; }
    }
    private ulong _bind_gold;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"bind_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bind_gold
    {
      get { return _bind_gold; }
      set { _bind_gold = value; }
    }
    private ulong _non_bind_diamond;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"non_bind_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong non_bind_diamond
    {
      get { return _non_bind_diamond; }
      set { _non_bind_diamond = value; }
    }
    private ulong _bind_diamond;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"bind_diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong bind_diamond
    {
      get { return _bind_diamond; }
      set { _bind_diamond = value; }
    }
    private uint _physical_strength;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"physical_strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint physical_strength
    {
      get { return _physical_strength; }
      set { _physical_strength = value; }
    }
    private ulong _fight_point;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"fight_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong fight_point
    {
      get { return _fight_point; }
      set { _fight_point = value; }
    }
    private uint _flags;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncRoleInfo_Ntf")]
  public partial class SMSG_SyncRoleInfo_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncRoleInfo_Ntf() {}
    
    private CharacterInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CharacterInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: hero.proto
namespace Games.PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _hero_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hero_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hero_id
    {
      get { return _hero_id; }
      set { _hero_id = value; }
    }
    private ulong _char_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"char_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong char_id
    {
      get { return _char_id; }
      set { _char_id = value; }
    }
    private uint _model_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"model_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint model_id
    {
      get { return _model_id; }
      set { _model_id = value; }
    }
    private uint _fashion_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fashion_id
    {
      get { return _fashion_id; }
      set { _fashion_id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private ulong _exp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SyncHeroList_Ntf")]
  public partial class SMSG_SyncHeroList_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_SyncHeroList_Ntf() {}
    
    private readonly global::System.Collections.Generic.List<HeroInfo> _hero_list = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"hero_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> hero_list
    {
      get { return _hero_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMSG_SelectInitializedHero_Req")]
  public partial class CMSG_SelectInitializedHero_Req : global::ProtoBuf.IExtensible
  {
    public CMSG_SelectInitializedHero_Req() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_SelectInitializedHero_Resp")]
  public partial class SMSG_SelectInitializedHero_Resp : global::ProtoBuf.IExtensible
  {
    public SMSG_SelectInitializedHero_Resp() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMSG_AddHero_Ntf")]
  public partial class SMSG_AddHero_Ntf : global::ProtoBuf.IExtensible
  {
    public SMSG_AddHero_Ntf() {}
    
    private HeroInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public HeroInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}